apiVersion: apis.apps.tanzu.vmware.com/v1alpha1
kind: APIDescriptor
metadata:
  name: customer-profile
  annotations:
    autoscaling.knative.dev/minScale: "1"
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: customer-profile
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: customer-profile
spec:
  type: openapi
  description: Manage customer profiles
  system: profile-management
  owner: customer-relations-department
  location:
    apiSpec:
      path: /api-docs
    server:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: customer-profile

