---
tap_install:
  secrets:
    eso:
      vault:
        server: http://vault.stuart-lab.com/
        namespace: ""
        auth:
          kubernetes:
            mountPath: vcf-view
            role: vcf-view--tap-install-secrets
      remote_refs:
        tap_sensitive_values:
          sensitive_tap_values_yaml:
            key: secret/dev/vcf-view/tap/sensitive-values.yaml
