---
tap_install:
  values:
    shared:
      ingress_domain: "apps.stuart-lab.com"
      # ingress_issuer: letsencrypt-production
      # ingress_issuer: my-company-ca
      kubernetes_version: "1.26.5"
      image_registry:
        project_path: "harbor.stuart-lab.com"
        secret:
          name: registries-credentials
      ca_cert_data: |
          # stu-ca
          -----BEGIN CERTIFICATE-----
          MIIFoDCCA4igAwIBAgIJAMJb+ENNEw4KMA0GCSqGSIb3DQEBCwUAMD0xCzAJBgNV
          BAYTAkNBMQswCQYDVQQIDAJPTjEQMA4GA1UECgwHc3R1LW9yZzEPMA0GA1UEAwwG
          c3R1LWNhMB4XDTIzMTAxNjE5MDExMVoXDTMzMTAxMzE5MDExMVowPTELMAkGA1UE
          BhMCQ0ExCzAJBgNVBAgMAk9OMRAwDgYDVQQKDAdzdHUtb3JnMQ8wDQYDVQQDDAZz
          dHUtY2EwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDRJp37c/pBQac0
          Ock9ZSR/b1jHrrZKjW7mP1U5+1A4x9egBEFITgyKHH1ETGw5axmM8mHFvItZbqF/
          iroPfEtLmT2sXuCcl2aD1jQrzIlSpp3DAQjxj/fTymARAgx9UmRxRNAC28z4XK04
          SXaWcntReBO+2qK6wA5XE2cuEV1Czz8CqFNNTk3mR2/uNDq0SonqvxqSynJNrmpr
          VSjcM340Df6p7At9DBB3LMrArBnwlm84lRpE8KXhaykKPcCLjWW75rXn3FuDx9W3
          sa59utRcGRpYwCeIXsCGHtWy9HLuEmmJBWNRUXhsvK4wHXGlKvyKOLJ6WwcQUeEG
          8MteUaF0vzC2k6TD6dIBDnZjkXsL0NVjp6Ov1txKQ0mUiCpYUOaMyYbimn3QeqwZ
          BcM+NbAhOvb3pOHucjtL9XAoW4v4t5jTeU29CchbZnj40NTOd7/C9RKMJ1cdFjAe
          WCiLNS556IqZs9DzT//B0KTrc1Qt2IAo9fTTW466GGEq4cUx/vK803H9S/NBiIIo
          1fXTsQ+gx0YTQjEbYmYLfkqvgBCP7OTyFLPNlZ4wQa51hFtvdusZvheHlHw/HNyG
          /CrJXGzhfIrQBqGs6PlGxpfmYUmB4U2FE2w+FccEWRgTH6/fwPdt9BQ9gKiUa5Q7
          Uqb1EX5FpqsM0o5hRQ8lUqRANxtDQQIDAQABo4GiMIGfMA8GA1UdEwEB/wQFMAMB
          Af8wHQYDVR0OBBYEFJx4niv5psA344VtBR6oqd7FcGC4MG0GA1UdIwRmMGSAFJx4
          niv5psA344VtBR6oqd7FcGC4oUGkPzA9MQswCQYDVQQGEwJDQTELMAkGA1UECAwC
          T04xEDAOBgNVBAoMB3N0dS1vcmcxDzANBgNVBAMMBnN0dS1jYYIJAMJb+ENNEw4K
          MA0GCSqGSIb3DQEBCwUAA4ICAQA5V2Xq06FiRwiNO1f3AzPXWXQIanCNVSNfIZ18
          M5D/CBi3HvtWSwziL8beWFi3UPhh3g1WonDPBzvNaEXjE8x53/YXKm/8xTvsq6HA
          aS7jGmhrUeT2LMDY8IcVzg/lrGU+LrXY0Xo012tLopPeEWwQ/3LVDnjxL+/Vq1vK
          BFhfq9LH1t0WwQe6NLv1i7QC4WwE7GO2EOcr12BRiXSxxce6i5+x71L7wrEzONID
          /cgt0zPu8nIABzZIUG9wF4LeEp2l9NntZrFFzVSwyfitl0L0qHULa3XmXf5SGthl
          exhgxJx+fvzTPiCeZVgXzVjAUEbSxR58fEZ1UdhHCPP4kWkszyXv5PagCwNepFy8
          rcHVhoZomezMYtapBWwFmQYfcjMYHyX6hDmR6XvonOKYBI1pC2FgiZEg1PmJnh7O
          pIcjNVW77IB/clh9+Pw1PL/OjXN/GFY/Kj8CauheiHmOtAMsS/dNx9T2F2qMsdZV
          6n48+veCyYKNg5795eL2pQfL6QureMBskYQ9Uds81WDdfiGIAWmOUR1SCejaazPT
          QVRUQ0zpxUmiVAxlut0tzc1yhGkYgybfXVYvPpIPXPtqra0YwSz44izDVJWQl6Ye
          t8UmeX/Z7zM4VSLRH1DRH/zs6LnSLGUadtQ3i8xIAkKzlo638RE3bh3LsdySH7jf
          /V4oWg==
          -----END CERTIFICATE-----
          # lets-encrypt
          -----BEGIN CERTIFICATE-----
          MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
          TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
          cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
          WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
          RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
          AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
          R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
          sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
          NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
          Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
          /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
          AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
          Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
          FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
          AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
          Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
          gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
          PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
          ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
          CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
          lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
          avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
          yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
          yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
          hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
          HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
          MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
          nLRbwHOoq7hHwg==
          -----END CERTIFICATE-----

    ceip_policy_disclosed: true
    profile: run # Can take full, iterate, build, run, view.

    supply_chain: basic # Can take testing, testing_scanning.

    contour:
      envoy:
        service:
          type: LoadBalancer

    # There is a bug in TAP 1.8.x. The policy-controller pkgi will fail to reconcile if this isn't set
    policy:
      tuf_enabled: true
     
    namespace_provisioner:
      controller: false
      gitops_install:
        ref: origin/main
        subPath: namespace-provisioner/run
        url:  git@jump.stuart-lab.com55:/home/git/tap-gitops.git
      # additional_sources:
      # - git:
      #     ref: origin/main
      #     subPath: namespace-provisioner/custom-resources/secrets/global
      #     url: https://dev.azure.com/crenaud0395/tap-gitops/_git/tap-gitops
      #   path: _ytt_lib/globalsecrets
      # import_data_values_secrets:
      # - name: sync-git
      #   namespace: tanzu-sync
      #   create_export: true

    excluded_packages:
      - learningcenter.tanzu.vmware.com
      - workshops.learningcenter.tanzu.vmware.com
      - fluxcd.source.controller.tanzu.vmware.com # This is installed through TMC instead