tap_install:
    sensitive_values:
        shared:
            image_registry:
                project_path: ENC[AES256_GCM,data:UagX0Dq8Se/iZp2YmeB9aJqe0J2bIV+z7eWgmSNKi3TcmDsu,iv:i6y/0sCPT6E/iy1wrrbCQFwyj5S1jMcLJZLq+HLvf28=,tag:XZr9UEKwSMrgZIDeOLeHUg==,type:str]
                username: ENC[AES256_GCM,data:2DBH/ryvXUX7xFabv7E=,iv:ma89H8Zb9pZR+q7HRGHZB7OxWN/u1uwJM6h14JCi29s=,tag:PTrylr8OvWNaV3gw9g68TA==,type:str]
                password: ENC[AES256_GCM,data:XilI59REglCHhOy5d8lUzICYxqriU0lekAhfFvnSJ7j1ceo77+zKN3Rc8ZbJ0w1dsDHQKg==,iv:EYWYJdgm/ryHkNlBA0LnCgGC5XDt4xfwZSCN3Fw6kbk=,tag:VzJC5GrkXQsvMxUV5E4fQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1awep5z86pe4dzg9aakspu8rv0ncpzhqz33t8hju3wme82y37vskq95yryk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNHhZanZGd0wzb0ZXSmo4
            VFN2dWxLSVRKR21ZT3BNb1ROOFhvckNPV0hvCjliVU5sR1FEYXVXMVRWRDE4K1cz
            clk4TE5na1pwZHFsOVZ6TlgvaHJ4eE0KLS0tIGxQWEt6dCtzVElweU1GUHkwVUYx
            Q21XTnN6SHdKQVZkVitnY3c0REcwS0kKM+pQRtJtgDqNpNqpVxG6iyNd3rck2TYh
            cL0MkEdMIc94USOCE9C96O42j+c2QVnLLTN7Av1HihE4cQzkd93Ldg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-01T16:50:59Z"
    mac: ENC[AES256_GCM,data:c7TUTcoPNLR1QF4LSi6qji7YHro5VJF+mfnD6oY/ElDMieucBBiU+xZVqLCIAnVL32yaaVi/Pij14Kh3/zob3H7f/rYODaUPBEuFKWTQJ5Xa8JkgER5UEoMMEuKVfDYSZKbWeqbT3Smjk548/1+0HZF1iWIADHoIN09FRCAWxXU=,iv:v0lN61g/VhYv6WIw/AqncISVMyu8WU3nD5+dEW6AkOQ=,tag:J1KH7IKBooWeZpltBR+6ig==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
