---
tap_install:
  values:
    # package_overlays:
    # - name: tap
    #   secrets:
    #   - name: tap-overlay

    ceip_policy_disclosed: true
    profile: full # Can take full, iterate, build, run, view.

    supply_chain: basic # Can take testing, testing_scanning.

    # ootb_templates:
    #   iaas_auth: true

    shared:
      ingress_domain: "stuart-lab.com"
      # ingress_issuer: letsencrypt-production
    #  ingress_issuer: my-company-ca
      kubernetes_version: "1.26.5"
      image_registry:
        project_path: "harbor.stuart-lab.com" # To be used by Build Service by appending "/buildservice" and used by Supply chain by appending "/workloads"
        secret:
          name: registries-credentials
      ca_cert_data: |
          # stu-ca
          -----BEGIN CERTIFICATE-----
          MIIFoDCCA4igAwIBAgIJAMJb+ENNEw4KMA0GCSqGSIb3DQEBCwUAMD0xCzAJBgNV
          BAYTAkNBMQswCQYDVQQIDAJPTjEQMA4GA1UECgwHc3R1LW9yZzEPMA0GA1UEAwwG
          c3R1LWNhMB4XDTIzMTAxNjE5MDExMVoXDTMzMTAxMzE5MDExMVowPTELMAkGA1UE
          BhMCQ0ExCzAJBgNVBAgMAk9OMRAwDgYDVQQKDAdzdHUtb3JnMQ8wDQYDVQQDDAZz
          dHUtY2EwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDRJp37c/pBQac0
          Ock9ZSR/b1jHrrZKjW7mP1U5+1A4x9egBEFITgyKHH1ETGw5axmM8mHFvItZbqF/
          iroPfEtLmT2sXuCcl2aD1jQrzIlSpp3DAQjxj/fTymARAgx9UmRxRNAC28z4XK04
          SXaWcntReBO+2qK6wA5XE2cuEV1Czz8CqFNNTk3mR2/uNDq0SonqvxqSynJNrmpr
          VSjcM340Df6p7At9DBB3LMrArBnwlm84lRpE8KXhaykKPcCLjWW75rXn3FuDx9W3
          sa59utRcGRpYwCeIXsCGHtWy9HLuEmmJBWNRUXhsvK4wHXGlKvyKOLJ6WwcQUeEG
          8MteUaF0vzC2k6TD6dIBDnZjkXsL0NVjp6Ov1txKQ0mUiCpYUOaMyYbimn3QeqwZ
          BcM+NbAhOvb3pOHucjtL9XAoW4v4t5jTeU29CchbZnj40NTOd7/C9RKMJ1cdFjAe
          WCiLNS556IqZs9DzT//B0KTrc1Qt2IAo9fTTW466GGEq4cUx/vK803H9S/NBiIIo
          1fXTsQ+gx0YTQjEbYmYLfkqvgBCP7OTyFLPNlZ4wQa51hFtvdusZvheHlHw/HNyG
          /CrJXGzhfIrQBqGs6PlGxpfmYUmB4U2FE2w+FccEWRgTH6/fwPdt9BQ9gKiUa5Q7
          Uqb1EX5FpqsM0o5hRQ8lUqRANxtDQQIDAQABo4GiMIGfMA8GA1UdEwEB/wQFMAMB
          Af8wHQYDVR0OBBYEFJx4niv5psA344VtBR6oqd7FcGC4MG0GA1UdIwRmMGSAFJx4
          niv5psA344VtBR6oqd7FcGC4oUGkPzA9MQswCQYDVQQGEwJDQTELMAkGA1UECAwC
          T04xEDAOBgNVBAoMB3N0dS1vcmcxDzANBgNVBAMMBnN0dS1jYYIJAMJb+ENNEw4K
          MA0GCSqGSIb3DQEBCwUAA4ICAQA5V2Xq06FiRwiNO1f3AzPXWXQIanCNVSNfIZ18
          M5D/CBi3HvtWSwziL8beWFi3UPhh3g1WonDPBzvNaEXjE8x53/YXKm/8xTvsq6HA
          aS7jGmhrUeT2LMDY8IcVzg/lrGU+LrXY0Xo012tLopPeEWwQ/3LVDnjxL+/Vq1vK
          BFhfq9LH1t0WwQe6NLv1i7QC4WwE7GO2EOcr12BRiXSxxce6i5+x71L7wrEzONID
          /cgt0zPu8nIABzZIUG9wF4LeEp2l9NntZrFFzVSwyfitl0L0qHULa3XmXf5SGthl
          exhgxJx+fvzTPiCeZVgXzVjAUEbSxR58fEZ1UdhHCPP4kWkszyXv5PagCwNepFy8
          rcHVhoZomezMYtapBWwFmQYfcjMYHyX6hDmR6XvonOKYBI1pC2FgiZEg1PmJnh7O
          pIcjNVW77IB/clh9+Pw1PL/OjXN/GFY/Kj8CauheiHmOtAMsS/dNx9T2F2qMsdZV
          6n48+veCyYKNg5795eL2pQfL6QureMBskYQ9Uds81WDdfiGIAWmOUR1SCejaazPT
          QVRUQ0zpxUmiVAxlut0tzc1yhGkYgybfXVYvPpIPXPtqra0YwSz44izDVJWQl6Ye
          t8UmeX/Z7zM4VSLRH1DRH/zs6LnSLGUadtQ3i8xIAkKzlo638RE3bh3LsdySH7jf
          /V4oWg==
          -----END CERTIFICATE-----
          # lets-encrypt
          -----BEGIN CERTIFICATE-----
          MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
          TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
          cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
          WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
          RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
          AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
          R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
          sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
          NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
          Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
          /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
          AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
          Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
          FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
          AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
          Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
          gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
          PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
          ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
          CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
          lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
          avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
          yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
          yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
          hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
          HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
          MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
          nLRbwHOoq7hHwg==
          -----END CERTIFICATE-----

    ootb_supply_chain_basic:
      registry:
        server: harbor.stuart-lab.com
        repository: appimages
      #   ca_cert_data: |
      # gitops:
      #   credentials_secret: "github-ssh-secret"
        # server_address: ssh://git@github.com/
        # repository_owner: stuartblackburnvmware
        # repository_name: tap-gitops
        # branch: main
        # commit_strategy: pull_request
        # pull_request:
        #   server_kind: github
        #   commit_branch: staging
        #   pull_request_title: ready for review title
        #   pull_request_body: generated by my amazing supply chain
      # scanning:
      #   image:
      #     template: snyk-private-image-scan-template
      #     policy: snyk-scan-policy
      #   source:
      #     template: blob-source-scan-template
      #     policy: scan-policy

    buildservice:
      kp_default_repository: harbor.stuart-lab.com/tanzu-application-platform/buildservice
      exclude_dependencies: true
      kp_default_repository_secret:
        name: registry-credentials
        namespace: tap-install
      # enable_automatic_dependency_updates: false

    contour:
      envoy:
        service:
          type: LoadBalancer
          
    # local_source_proxy:
    #   # Takes the value from the project_path under the image_registry section of shared by default, but can be overridden by setting a different value.
    #   repository: "harbor.stuart-lab.com/lsp"
    #   push_secret:
    #     # When set to true, the secret mentioned in this section is automatically exported to Local Source Proxy's namespace.
    #     name: lsp-push-credentials
    #     namespace: tap-install
    #     # When set to true, the secret mentioned in this section is automatically exported to Local Source Proxy's namespace.
    #     create_export: true

    ootb_delivery_basic:
      service_account: default

    tap_gui:
      ingressEnabled: true
      ingressDomain: stuart-lab.com
      app_config:
        supplyChain:
          enablePlugin: true
        auth:
          environment: development
          loginPage:
            github:
              title: Github Login
              message: Enter with your GitHub account yo
          allowGuestAccess: false
        backend:
          baseUrl: https://tap-gui.stuart-lab.com
          cors:
            origin: https://tap-gui.stuart-lab.com
    #      database:
    #        client: pg
    #        prefix: tap-gui-
    #        connection:
    #          host: postgres.database.azure.com
    #          port: 5432
    #          user: stutappostgres
    #          password: xxx
    #          ssl: {rejectUnauthorized: false} # Set to true if using SSL
        app:
          baseUrl: https://tap-gui.stuart-lab.com
          title: 'TAP TAP TAP'
          support:
            url: www.leavemealone.com
            items:
              - title: Contact Support (or don't)
                icon: email
                links:
                  - url: https://fakeurl.com
                    title: Nobody is going to support you
              - title: Documentation
                icon: docs
                links:
                  - url: https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/index.html
                    title: Tanzu Application Platform Documentation (testy test test)
        organization:
          name: 'My Amazing Org'
        catalog:
          # locations:
          #   # This doesn't work because I'm getting the following error in my tap-gui pod:
          #   # entry of type github-discovery, but does not have the corresponding catalog processor GithubDiscoveryProcessor installed
          #   # Need to figure this out. In the meantime, just register workloads in the gui manually
          #   - type: github-discovery
          #     target: https://github.com/stuartblackburnvmware/*/blob/main/catalog/catalog-info.yaml

    metadata_store:
      ingress_enabled: "true"
      ingress_domain: "stuart-lab.com"
      app_service_type: ClusterIP
      ns_for_export_app_cert: "*" ###should this change?
      # storage_class_name: vc01cl01-t0compute
      # db_host: "postgres.database.azure.com"
      # db_user: "stutappostgres"
      # db_password: "xxx"
      # db_name: "metadata-store"
      # db_port: "5432"
      # db_sslmode: "verify-full"
      # db_max_open_conns: 10
      # db_max_idle_conns: 100
      # db_conn_max_lifetime: 60
      # db_ca_certificate: |
      #   -----BEGIN CERTIFICATE-----
      #   MIIDrzCCApegAwIBAgIQCDvgVpBCRrGhdWrJWZHHSjANBgkqhkiG9w0BAQUFADBh
      #   MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
      #   d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBD
      #   QTAeFw0wNjExMTAwMDAwMDBaFw0zMTExMTAwMDAwMDBaMGExCzAJBgNVBAYTAlVT
      #   MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j
      #   b20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IENBMIIBIjANBgkqhkiG
      #   9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4jvhEXLeqKTTo1eqUKKPC3eQyaKl7hLOllsB
      #   CSDMAZOnTjC3U/dDxGkAV53ijSLdhwZAAIEJzs4bg7/fzTtxRuLWZscFs3YnFo97
      #   nh6Vfe63SKMI2tavegw5BmV/Sl0fvBf4q77uKNd0f3p4mVmFaG5cIzJLv07A6Fpt
      #   43C/dxC//AH2hdmoRBBYMql1GNXRor5H4idq9Joz+EkIYIvUX7Q6hL+hqkpMfT7P
      #   T19sdl6gSzeRntwi5m3OFBqOasv+zbMUZBfHWymeMr/y7vrTC0LUq7dBMtoM1O/4
      #   gdW7jVg/tRvoSSiicNoxBN33shbyTApOB6jtSj1etX+jkMOvJwIDAQABo2MwYTAO
      #   BgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUA95QNVbR
      #   TLtm8KPiGxvDl7I90VUwHwYDVR0jBBgwFoAUA95QNVbRTLtm8KPiGxvDl7I90VUw
      #   DQYJKoZIhvcNAQEFBQADggEBAMucN6pIExIK+t1EnE9SsPTfrgT1eXkIoyQY/Esr
      #   hMAtudXH/vTBH1jLuG2cenTnmCmrEbXjcKChzUyImZOMkXDiqw8cvpOp/2PV5Adg
      #   06O/nVsJ8dWO41P0jmP6P6fbtGbfYmbW0W5BjfIttep3Sp+dWOIrWcBAI+0tKIJF
      #   PnlUkiaY4IBIqDfv8NZ5YBberOgOzW6sRBc4L0na4UU+Krk2U886UAb3LujEV0ls
      #   YSEY1QSteDwsOoBrp+uvFRTp2InBuThs4pFsiv9kuXclVzDAGySj4dzp30d8tbQk
      #   CAUw7C29C79Fv1C5qfPrmAESrciIxpg0X40KPMbp1ZWVbd4=
      #   -----END CERTIFICATE-----

      # deploy_internal_db: "false"

    # scanning:
    #   metadataStore:
    #     url: "" # Configuration is moved, so set this string to empty.

    accelerator:
      server:
        service_type: "ClusterIP"

    cnrs:
      domain_name: stuart-lab.com

    namespace_provisioner:
      controller: true
      default_parameters:
        supply_chain_service_account:
          secrets:
          - github-ssh-secret
          - github-http-secret
          # - stu-cosign-key-pair

    appliveview:
      backend:
        ingressEnabled: true
        # sslDeactivated: false
        # host: appliveview.stuart-lab.com
        # caCertData: |-
        #   -----BEGIN CERTIFICATE-----
        #   MIIFoDCCA4igAwIBAgIJAMJb+ENNEw4KMA0GCSqGSIb3DQEBCwUAMD0xCzAJBgNV
        #   BAYTAkNBMQswCQYDVQQIDAJPTjEQMA4GA1UECgwHc3R1LW9yZzEPMA0GA1UEAwwG
        #   c3R1LWNhMB4XDTIzMTAxNjE5MDExMVoXDTMzMTAxMzE5MDExMVowPTELMAkGA1UE
        #   BhMCQ0ExCzAJBgNVBAgMAk9OMRAwDgYDVQQKDAdzdHUtb3JnMQ8wDQYDVQQDDAZz
        #   dHUtY2EwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDRJp37c/pBQac0
        #   Ock9ZSR/b1jHrrZKjW7mP1U5+1A4x9egBEFITgyKHH1ETGw5axmM8mHFvItZbqF/
        #   iroPfEtLmT2sXuCcl2aD1jQrzIlSpp3DAQjxj/fTymARAgx9UmRxRNAC28z4XK04
        #   SXaWcntReBO+2qK6wA5XE2cuEV1Czz8CqFNNTk3mR2/uNDq0SonqvxqSynJNrmpr
        #   VSjcM340Df6p7At9DBB3LMrArBnwlm84lRpE8KXhaykKPcCLjWW75rXn3FuDx9W3
        #   sa59utRcGRpYwCeIXsCGHtWy9HLuEmmJBWNRUXhsvK4wHXGlKvyKOLJ6WwcQUeEG
        #   8MteUaF0vzC2k6TD6dIBDnZjkXsL0NVjp6Ov1txKQ0mUiCpYUOaMyYbimn3QeqwZ
        #   BcM+NbAhOvb3pOHucjtL9XAoW4v4t5jTeU29CchbZnj40NTOd7/C9RKMJ1cdFjAe
        #   WCiLNS556IqZs9DzT//B0KTrc1Qt2IAo9fTTW466GGEq4cUx/vK803H9S/NBiIIo
        #   1fXTsQ+gx0YTQjEbYmYLfkqvgBCP7OTyFLPNlZ4wQa51hFtvdusZvheHlHw/HNyG
        #   /CrJXGzhfIrQBqGs6PlGxpfmYUmB4U2FE2w+FccEWRgTH6/fwPdt9BQ9gKiUa5Q7
        #   Uqb1EX5FpqsM0o5hRQ8lUqRANxtDQQIDAQABo4GiMIGfMA8GA1UdEwEB/wQFMAMB
        #   Af8wHQYDVR0OBBYEFJx4niv5psA344VtBR6oqd7FcGC4MG0GA1UdIwRmMGSAFJx4
        #   niv5psA344VtBR6oqd7FcGC4oUGkPzA9MQswCQYDVQQGEwJDQTELMAkGA1UECAwC
        #   T04xEDAOBgNVBAoMB3N0dS1vcmcxDzANBgNVBAMMBnN0dS1jYYIJAMJb+ENNEw4K
        #   MA0GCSqGSIb3DQEBCwUAA4ICAQA5V2Xq06FiRwiNO1f3AzPXWXQIanCNVSNfIZ18
        #   M5D/CBi3HvtWSwziL8beWFi3UPhh3g1WonDPBzvNaEXjE8x53/YXKm/8xTvsq6HA
        #   aS7jGmhrUeT2LMDY8IcVzg/lrGU+LrXY0Xo012tLopPeEWwQ/3LVDnjxL+/Vq1vK
        #   BFhfq9LH1t0WwQe6NLv1i7QC4WwE7GO2EOcr12BRiXSxxce6i5+x71L7wrEzONID
        #   /cgt0zPu8nIABzZIUG9wF4LeEp2l9NntZrFFzVSwyfitl0L0qHULa3XmXf5SGthl
        #   exhgxJx+fvzTPiCeZVgXzVjAUEbSxR58fEZ1UdhHCPP4kWkszyXv5PagCwNepFy8
        #   rcHVhoZomezMYtapBWwFmQYfcjMYHyX6hDmR6XvonOKYBI1pC2FgiZEg1PmJnh7O
        #   pIcjNVW77IB/clh9+Pw1PL/OjXN/GFY/Kj8CauheiHmOtAMsS/dNx9T2F2qMsdZV
        #   6n48+veCyYKNg5795eL2pQfL6QureMBskYQ9Uds81WDdfiGIAWmOUR1SCejaazPT
        #   QVRUQ0zpxUmiVAxlut0tzc1yhGkYgybfXVYvPpIPXPtqra0YwSz44izDVJWQl6Ye
        #   t8UmeX/Z7zM4VSLRH1DRH/zs6LnSLGUadtQ3i8xIAkKzlo638RE3bh3LsdySH7jf
        #   /V4oWg==
        #   -----END CERTIFICATE-----

    excluded_packages:
    #  - image-policy-webhook.signing.apps.tanzu.vmware.com
      - learningcenter.tanzu.vmware.com
      - workshops.learningcenter.tanzu.vmware.com
      - fluxcd.source.controller.tanzu.vmware.com # This is installed through TMC instead

    # tap_telemetry:
    #   customer_entitlement_account_number: "12345"