tap_install:
  package_repository:
    oci_repository: stutapregistry.azurecr.io/tapimages
  version:
      package_repo_bundle_tag: "1.6.1" # Populate these values with the latest patch version.
      package_version: "1.6.1"