apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: node-express
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: node-express
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: node-express
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/debug: "true"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          developer-conventions/add-source-image-label
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.apps.tanzu.vmware.com/image-source-digest: main@sha1:36a5a6be31d01ce31d0a41be0b7e9012a594632f
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: node-express
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: node-express
    spec:
      containers:
      - image: stutapregistry.azurecr.io/appimages/node-express-stu-ns@sha256:4f9dea5ae6946794722f6dd440a871c0b24adc6f39f6dd1ed51fab212e32859c
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

