tap_install:
  package_repository:
    oci_repository: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages
  version:
      package_repo_bundle_tag: "1.6.4" # Populate these values with the latest patch version.
      package_version: "1.6.4"
