apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: stu-public-python-app.stu-ns.tap.20240104194136.0.0+build.fc5838b
spec:
  refName: stu-public-python-app.stu-ns.tap
  version: 20240104194136.0.0+build.fc5838b
  releaseNotes: |
    Release v20240104194136.0.0+build.fc5838b of package stu-public-python-app.stu-ns.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harbor.h2o-2-21258.h2o.vmware.com/tap/workloads/stu-public-python-app-stu-ns-bundle@sha256:76d6521158bebbcfd99b6ae8c80c85231918608948ed4423de4d6f9baab3d602
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

