---
tap_install:
  secrets:
    eso:
      vault:
        server: http://vault.stuart-lab.com/
        namespace: ""
        auth:
          kubernetes:
            mountPath: vcf-run
            role: vcf-run--tap-install-secrets
      remote_refs:
        tap_sensitive_values:
          sensitive_tap_values_yaml:
            key: secret/dev/vcf-run/tap/sensitive-values.yaml
