apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: stu-public-python-app
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: stu-public-python-app
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: stu-public-python-app
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/debug: "true"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          developer-conventions/add-source-image-label
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.apps.tanzu.vmware.com/image-source-digest: main@sha1:3675164ce80cdf4b75c874a4b20ad6694e92b3df
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: stu-public-python-app
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: stu-public-python-app
    spec:
      containers:
      - image: stutapregistry.azurecr.io/tapimages/stu-public-python-app-stu-ns@sha256:ad0b4ed1aa15303ed1e90e60c2dc2d11da66a704cfaf98558b44cfedef810a59
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

